baseURL = "https://gopallin.github.io/"
languageCode = "zh-tw"
title = "A Litte More Every Day"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "雙木林雙先生"
  description = "大學讀工業工管；曾半路出家做電控；現職為軟體工程師。在這裡分享一些工作之餘做的小專案🤡也滿足小時候想當作家的幻想🙉"
  github = "gopallin"
  email = "btoeww1993@gmail.com"
  url = "https://github.com/gopallin"
  favicon = "/images/github-mark.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/github-mark-white.png"
  location = "Tawian"
  userStatusEmoji = "😬"
  enableGitalk = true
  enableSearch = true

  [params.gitalk]
    clientID = "Your client ID"
    clientSecret = "Your client secret" # Your client secret
    repo = "LuvSia"
    owner = "ventusoon"
    admin = "ventusoon"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # 可以自行添加反向代理

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    # ID = "UA-123456-789"

[environments]
  [environments.development]
    baseURL = "http://localhost:1313/"
